Update docker-entrypoint.sh
--cmake-args -DBUILD_TESTING=OFF

Avoid: 
```bash
/root/ws_moveit/src/image_common/image_transport/test/test_remapping.cpp:22:13: error: ‘NodeOptions’ is not a member of ‘rclcpp’
rclcpp::NodeOptions node_options;
```

Introduced at: https://github.com/ros-perception/image_common/commit/b86edf5723e0a4ab15f770c685a6001717f84205